tasks:
  - name: all-commands
  - name: run-airflow
    openMode: split-right
  - name: spark-master
    openMode: split-right
ports:
  - port: 8081
    onOpen: open-browser
  - port: 8080
    onOpen: open-browser
  - port: 8793
    onOpen: ignore
